// <auto-generated />
namespace Project.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shkatula_lalka_jibana : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shkatula_lalka_jibana));
        
        string IMigrationMetadata.Id
        {
            get { return "201606191734186_shkatula_lalka_jibana"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
